### ISSUE TITLE
GitHub Flavored Markdown Examples

### ISSUE THREAD

**Issue by mojombo** [mojombo/github-flavored-markdown#1]
# GitHub Flavored Markdown

_View the [source of this content](http://github.github.com/github-flavored-markdown/sample_content.html)._

Let's get the whole "linebreak" thing out of the way. The next paragraph contains two phrases separated by a single newline character:

Roses are red
Violets are blue

The next paragraph has the same phrases, but now they are separated by two spaces and a newline character:

Roses are red  
Violets are blue

Oh, and one thing I cannot stand is the mangling of words with multiple underscores in them like perform_complicated_task or do_this_and_do_that_and_another_thing.
## A bit of the GitHub spice

In addition to the changes in the previous section, certain references are auto-linked:
- SHA: be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User@SHA ref: mojombo@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User/Project@SHA: mojombo/god@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- #Num: #1
- User/#Num: mojombo#1
- User/Project#Num: mojombo/god#1

These are dangerous goodies though, and we need to make sure email addresses don't get mangled:

My email addy is tom@github.com.
## Math is hard, let's go shopping

In first grade I learned that 5 > 3 and 2 < 7. Maybe some arrows. 1 -> 2 -> 3. 9 <- 8 <- 7.

Triangles man! a^2 + b^2 = c^2
## We all like making lists

The above header should be an H2 tag. Now, for a list of fruits:
- Red Apples
- Purple Grapes
- Green Kiwifruits

Let's get crazy:
1.  This is a list item with two paragraphs. Lorem ipsum dolor
   sit amet, consectetuer adipiscing elit. Aliquam hendrerit
   mi posuere lectus.
   
   Vestibulum enim wisi, viverra nec, fringilla in, laoreet
   vitae, risus. Donec sit amet nisl. Aliquam semper ipsum
   sit amet velit.
2.  Suspendisse id sem consectetuer libero luctus adipiscing.

What about some code **in** a list? That's insane, right?
1. In Ruby you can map like this:
   
   ```
   ['a', 'b'].map { |x| x.uppercase }
   ```
2. In Rails, you can do a shortcut:
   
   ```
   ['a', 'b'].map(&:uppercase)
   ```

Some people seem to like definition lists

<dl>
  <dt>Lower cost</dt>
  <dd>The new version of this product costs significantly less than the previous one!</dd>
  <dt>Easier to use</dt>
  <dd>We've changed the product so that it's much easier to use!</dd>
</dl>

## I am a robot

Maybe you want to print `robot` to the console 1000 times. Why not?

```
def robot_invasion
  puts("robot " * 1000)
end
```

You see, that was formatted as code because it's been indented by four spaces.

How about we throw some angle braces and ampersands in there?

```
<div class="footer">
    &copy; 2004 Foo Corporation
</div>
```
## Set in stone

Preformatted blocks are useful for ASCII art:

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-< 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>

## Playing the blame game

If you need to blame someone, the best way to do so is by quoting them:

> I, at any rate, am convinced that He does not throw dice.

Or perhaps someone a little less eloquent:

> I wish you'd have given me this written question ahead of time so I
> could plan for it... I'm sure something will pop into my head here in
> the midst of this press conference, with all the pressure of trying to
> come up with answer, but it hadn't yet...
> 
> I don't want to sound like
> I have made no mistakes. I'm confident I have. I just haven't - you
> just put me under the spot here, and maybe I'm not as quick on my feet
> as I should be in coming up with one.
## Table for two

<table>
  <tr>
    <th>ID</th><th>Name</th><th>Rank</th>
  </tr>
  <tr>
    <td>1</td><td>Tom Preston-Werner</td><td>Awesome</td>
  </tr>
  <tr>
    <td>2</td><td>Albert Einstein</td><td>Nearly as awesome</td>
  </tr>
</table>

## Crazy linking action

I get 10 times more traffic from [Google](http://google.com/) than from
[Yahoo](http://search.yahoo.com/) or [MSN](http://search.msn.com/).

Also, shoop.

**Comment by kennethreitz** [comment]
I want this in php!!!

**Comment by mojombo** [comment]
Easy enough. Here's the Ruby code that we use. It should be simple to port to PHP.

http://gist.github.com/118964

**Comment by fgnass** [comment]
Looks like the arrows/math example doesn't work.

**Comment by fgnass** [comment]
Oh, therefore HTML (a subset?) seems to be supported in comments ;-)

**Comment by fgnass** [comment]
Sorry my fault, I wasn't aware that Markdown also supports regular HTML tags.
Anyway, the a^2 and arrow -> syntax mentioned in the example doesn't seem to work.

**Comment by perj** [comment]
Doesn't seem to parse valgrind reports very well, eg. http://github.com/facebook/hiphop-php/issues/#issue/50 a bit down. Nor gdb tracebacks for that matter.

**Comment by snoldak924** [comment]
a^2 works for me, but not ->

Fedora 12, FF 3.5.11

**Comment by Archeleus** [comment]
Yeah, arrows don't work.

**Comment by najamelan** [comment]
any chance on images? Being able to upload a screenshot in an issue tracker is quite useful

**Comment by paradoxxxzero** [comment]
For images : http://daringfireball.net/projects/markdown/syntax#img

**Comment by cjxgm** [comment]
I **like** _this_ feeling...

> Maybe there's something wrong in the page.
> 
> Under `Set in stone`.
> 
> And `->` doesn't work on my computer, too.

```
Yeah, I like to try these.
```

> f(x) = sin(ax^2 ) + bx + c

OK

> That's _it_!
> 1. abcdef
>    ghijklmnopq
> 2. cdefg
> - abc
> - cde

**Comment by ekd123** [comment]
**B**

_I_

**_BI**_

_What is this?_

*xxx* is same as _xxx_?

**Comment by woomla** [comment]
<pre>
And this is ?
</pre>

**Comment by Rosuav** [comment]
Something seems to be wrong with the ASCII art example; I think it's coming out as code but not pre.

**Comment by carlosalexsander** [comment]
[testing]

**Comment by carlosalexsander** [comment]
<pre> teste </pre>

**Comment by dnadlinger** [comment]
Isn't the above rendering pretty much broken?

**Comment by ghost** [comment]
This Api's Tester

**Comment by sanek83** [comment]
![logo](https://a248.e.akamai.net/assets.github.com/images/modules/header/logov6-hover.svg)

**Comment by SethMilliken** [comment]
Given that this page is offered as the primary example linked from the [GitHub Flavored Markdown](http://github.github.com/github-flavored-markdown/) page, it would be great if it rendered correctly. So thanks to the wonderful fact that comments themselves use this very markdown, I've included a c&p of the [corresponding referenced source](http://github.github.com/github-flavored-markdown/sample_content.html) (with the exception of the following minor fix, `s/</&lt;/`, in the `<pre>` example which appears to be indicative of what is arguably a bug in the `<pre>` parsing code):

## Begin Example Source of Corrected `<pre>` Section

---

```
<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-&lt; 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>
```

## Begin Full Rendered Source

---

# GitHub Flavored Markdown

_View the [source of this content](http://github.github.com/github-flavored-markdown/sample_content.html)._

Let's get the whole "linebreak" thing out of the way. The next paragraph contains two phrases separated by a single newline character:

Roses are red
Violets are blue

The next paragraph has the same phrases, but now they are separated by two spaces and a newline character:

Roses are red  
Violets are blue

Oh, and one thing I cannot stand is the mangling of words with multiple underscores in them like perform_complicated_task or do_this_and_do_that_and_another_thing.

## A bit of the GitHub spice

In addition to the changes in the previous section, certain references are auto-linked:
- SHA: be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User@SHA ref: mojombo@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User/Project@SHA: mojombo/god@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- #Num: #1
- User/#Num: mojombo#1
- User/Project#Num: mojombo/god#1

These are dangerous goodies though, and we need to make sure email addresses don't get mangled:

My email addy is tom@github.com.

## Math is hard, let's go shopping

In first grade I learned that 5 > 3 and 2 < 7. Maybe some arrows. 1 -> 2 -> 3. 9 <- 8 <- 7.

Triangles man! a^2 + b^2 = c^2

## We all like making lists

The above header should be an H2 tag. Now, for a list of fruits:
- Red Apples
- Purple Grapes
- Green Kiwifruits

Let's get crazy:
1.  This is a list item with two paragraphs. Lorem ipsum dolor
   sit amet, consectetuer adipiscing elit. Aliquam hendrerit
   mi posuere lectus.
   
   Vestibulum enim wisi, viverra nec, fringilla in, laoreet
   vitae, risus. Donec sit amet nisl. Aliquam semper ipsum
   sit amet velit.
2.  Suspendisse id sem consectetuer libero luctus adipiscing.

What about some code **in** a list? That's insane, right?
1. In Ruby you can map like this:
   
   ```
   ['a', 'b'].map { |x| x.uppercase }
   ```
2. In Rails, you can do a shortcut:
   
   ```
   ['a', 'b'].map(&:uppercase)
   ```

Some people seem to like definition lists

<dl>
  <dt>Lower cost</dt>
  <dd>The new version of this product costs significantly less than the previous one!</dd>
  <dt>Easier to use</dt>
  <dd>We've changed the product so that it's much easier to use!</dd>
</dl>


## I am a robot

Maybe you want to print `robot` to the console 1000 times. Why not?

```
def robot_invasion
  puts("robot " * 1000)
end
```

You see, that was formatted as code because it's been indented by four spaces.

How about we throw some angle braces and ampersands in there?

```
<div class="footer">
    &copy; 2004 Foo Corporation
</div>
```

## Set in stone

Preformatted blocks are useful for ASCII art:

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-&lt; 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>


## Playing the blame game

If you need to blame someone, the best way to do so is by quoting them:

> I, at any rate, am convinced that He does not throw dice.

Or perhaps someone a little less eloquent:

> I wish you'd have given me this written question ahead of time so I
> could plan for it... I'm sure something will pop into my head here in
> the midst of this press conference, with all the pressure of trying to
> come up with answer, but it hadn't yet...
> 
> I don't want to sound like
> I have made no mistakes. I'm confident I have. I just haven't - you
> just put me under the spot here, and maybe I'm not as quick on my feet
> as I should be in coming up with one.

## Table for two

<table>
  <tr>
    <th>ID</th><th>Name</th><th>Rank</th>
  </tr>
  <tr>
    <td>1</td><td>Tom Preston-Werner</td><td>Awesome</td>
  </tr>
  <tr>
    <td>2</td><td>Albert Einstein</td><td>Nearly as awesome</td>
  </tr>
</table>


## Crazy linking action

I get 10 times more traffic from [Google](http://google.com/) than from
[Yahoo](http://search.yahoo.com/) or [MSN](http://search.msn.com/).

**Comment by panzi** [comment]
The table feature seems to be broken. At least the tables here do not work:
https://github.com/panzi/SocialSharePrivacy

I'll test some things here:

<table>
<thead>
<tr>
<th>Character</th>
<th>Replacement</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>&lt;</code></td>
<td><code>&amp;lt;</code></td>
</tr>
<tr>
<td><code>&gt;</code></td>
<td><code>&amp;gt;</code></td>
</tr>
<tr>
<td><code>&amp;</code></td>
<td><code>&amp;amp;</code></td>
</tr>
<tr>
<td><code>"</code></td>
<td><code>&amp;quot;</code></td>
</tr>
<tr>
<td><code>'</code></td>
<td><code>&amp;#39;</code></td>
</tr>
</tbody>
</table>


<table>
<tr>
<th>Character</th>
<th>Replacement</th>
</tr>
<tr>
<td><code>&lt;</code></td>
<td><code>&amp;lt;</code></td>
</tr>
<tr>
<td><code>&gt;</code></td>
<td><code>&amp;gt;</code></td>
</tr>
<tr>
<td><code>&amp;</code></td>
<td><code>&amp;amp;</code></td>
</tr>
<tr>
<td><code>"</code></td>
<td><code>&amp;quot;</code></td>
</tr>
<tr>
<td><code>'</code></td>
<td><code>&amp;#39;</code></td>
</tr>
</table>

**Comment by panzi** [comment]
<table>
<thead>
<tr>
<th>Character</th>
<th>Replacement</th>
</tr>
</thead>
<tbody>
<tr>
<td>&lt;</td>
<td>&amp;lt;</td>
</tr>
</tbody>
</table>


<table>
<tr>
<th>Character</th>
<th>Replacement</th>
</tr>
<tr>
<td>&lt;</td>
<td>&amp;lt;</td>
</tr>
</table>


<table>
<tr>
<td>Character</td>
<td>Replacement</td>
</tr>
<tr>
<td>Foo</td>
<td>Bar</td>
</tr>
</table>

**Comment by panzi** [comment]
Nope, completely broken.

**Comment by panzi** [comment]
Last try:

<table>
<tr>
<td>Foo</td>
<td>Bar</td>
</tr>
<tr>
<td>Egg</td>
<td>Spam</td>
</tr>
</table>

**Comment by panzi** [comment]
Or do all &lt;td&gt;s need to be in one line?

<table>
<tbody>
<tr>
<td>Foo</td><td>Bar</td>
</tr>
<tr>
<td>Foo</td><td>Bar</td>
</tr>
</tbody>
</table>


<table>
<tr>
<td>Foo</td><td>Bar</td>
</tr>
<tr>
<td>Foo</td><td>Bar</td>
</tr>
</table>

**Comment by FichteFoll** [comment]
https://github.com/FichteFoll/sublimetext-insertdate/blob/master/README.md

Seems to be similar to the "MultiMarkDown" thing but I'm not sure about that and it just works. The alignments do not, apparently (the `:----`, `:-----:` `------:` thing).

Edit: [Plugin](https://gist.github.com/2663710) for Sublime Tex 2.

**Comment by panzi** [comment]
Ok, then let me try this here:

| Foo | Bar |
| :-- | :-- |
| Egg | Spam |

... interestingly it shows the exact same problems as the &lt;table&gt; version. My guess is that sometime in the last few days some update wrecked table support on github and that old files are cached rendered and thus still look right.

When you click on "Edit" and then on "Preview" in the README.md you linked you see the exact same thing.

**Comment by FichteFoll** [comment]
Yeah, seems to be fixed now.

**Comment by tsatalos** [comment]
It seems that un-necessary parsing happens within preformatted blocks < pre > ...< /pre >
For example the existance of a single '&' in the preformated block causes a parse error to be generated and the whole pre formatted block to become pink....

To avoid that you need to replace all your ampersands within pre with & amp ; ...
I am assuming that this is a parsing bug of the markdown library and not a standard behavior, correct?

odysseas

**Comment by yatharth** [comment]
# Broken

This _soo_ doesn't work properly. And they still don't allow HTML inside `<del>code<del>` tags (which is probably a feature, not a bug). And as a [previous commenter](https://github.com/SethMilliken) [said](https://github.com/mojombo/github-flavored-markdown/issues/1#issuecomment-4525906):

> Given that this page is offered as the primary example linked from the GitHub Flavored Markdown page, it would be great if it rendered correctly.

So I decided to try it on my own :)

# GitHub Flavored Markdown

_View the [source of this content](http://github.github.com/github-flavored-markdown/sample_content.html)._

Let's get the whole "linebreak" thing out of the way. The next paragraph contains two phrases separated by a single newline character:

Roses are red
Violets are blue

The next paragraph has the same phrases, but now they are separated by two spaces and a newline character:

Roses are red  
Violets are blue

Oh, and one thing I cannot stand is the mangling of words with multiple underscores in them like perform_complicated_task or do_this_and_do_that_and_another_thing.

## A bit of the GitHub spice

In addition to the changes in the previous section, certain references are auto-linked:
- SHA: be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User@SHA ref: mojombo@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User/Project@SHA: mojombo/god@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- #Num: #1
- User/#Num: mojombo#1
- User/Project#Num: mojombo/god#1

These are dangerous goodies though, and we need to make sure email addresses don't get mangled:

My email addy is tom@github.com.

## Math is hard, let's go shopping

In first grade I learned that 5 > 3 and 2 < 7. Maybe some arrows. 1 -> 2 -> 3. 9 <- 8 <- 7.

Triangles man! a^2 + b^2 = c^2

## We all like making lists

The above header should be an H2 tag. Now, for a list of fruits:
- Red Apples
- Purple Grapes
- Green Kiwifruits

Let's get crazy:
1.  This is a list item with two paragraphs. Lorem ipsum dolor
   sit amet, consectetuer adipiscing elit. Aliquam hendrerit
   mi posuere lectus.
   
   Vestibulum enim wisi, viverra nec, fringilla in, laoreet
   vitae, risus. Donec sit amet nisl. Aliquam semper ipsum
   sit amet velit.
2.  Suspendisse id sem consectetuer libero luctus adipiscing.

What about some code **in** a list? That's insane, right?
1. In Ruby you can map like this:
   
   ```
   ['a', 'b'].map { |x| x.uppercase }
   ```
2. In Rails, you can do a shortcut:
   
   ```
   ['a', 'b'].map(&:uppercase)
   ```

Some people seem to like definition lists

<dl>
  <dt>Lower cost</dt>
  <dd>The new version of this product costs significantly less than the previous one!</dd>
  <dt>Easier to use</dt>
  <dd>We've changed the product so that it's much easier to use!</dd>
</dl>


## I am a robot

Maybe you want to print `robot` to the console 1000 times. Why not?

```
def robot_invasion
  puts("robot " * 1000)
end
```

You see, that was formatted as code because it's been indented by four spaces.

How about we throw some angle braces and ampersands in there?

```
<div class="footer">
    &copy; 2004 Foo Corporation
</div>
```

## Set in stone

Preformatted blocks are useful for ASCII art:

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-&lt; 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>


## Playing the blame game

If you need to blame someone, the best way to do so is by quoting them:

> I, at any rate, am convinced that He does not throw dice.

Or perhaps someone a little less eloquent:

> I wish you'd have given me this written question ahead of time so I
> could plan for it... I'm sure something will pop into my head here in
> the midst of this press conference, with all the pressure of trying to
> come up with answer, but it hadn't yet...
> 
> I don't want to sound like
> I have made no mistakes. I'm confident I have. I just haven't - you
> just put me under the spot here, and maybe I'm not as quick on my feet
> as I should be in coming up with one.

## Table for two

<table>
  <tr>
    <th>ID</th><th>Name</th><th>Rank</th>
  </tr>
  <tr>
    <td>1</td><td>Tom Preston-Werner</td><td>Awesome</td>
  </tr>
  <tr>
    <td>2</td><td>Albert Einstein</td><td>Nearly as awesome</td>
  </tr>
</table>


## Crazy linking action

I get 10 times more traffic from [Google](http://google.com/) than from
[Yahoo](http://search.yahoo.com/) or [MSN](http://search.msn.com/).

**Comment by jasam-xm** [comment]
Good easy to use!

**Comment by touhonoob** [comment]
# 

## 

=_=
-.-

**Comment by lu-zero** [comment]
Why the
:   syntax is not supported?

<dl>
  <dt>Lower cost</dt>
  <dd>The new version of this product costs significantly less than the previous one!</dd>
  <dt>Easier to use</dt>
  <dd>We've changed the product so that it's much easier to use!</dd>
</dl>

Is less compact...

**Comment by redfish88** [comment]
# test

`code`

```
 public class People{
  private String name;
  private  int     age;
 }
```

## i am a coder

<table>
<tr><th>language</th></tr>
<tr><td>java</td></tr>
<tr><td>python</td></tr>
</table>

## very good

**Comment by joellimberg** [comment]
Again: the example shown in the posted issue has many rendering problems.
- "certain references are auto-linked" – nope
- and the arrow example is parsed incorrectly, and now shows text w/ strikethrough.

**Comment by serpulga** [comment]
How do I apply italics + bold?

**Comment by FichteFoll** [comment]
**_both**_

```
***both***
```

**Comment by serpulga** [comment]
Doesn't work for me in a README. :(

**Comment by nishp1** [comment]
# GitHub Flavored Markdown

_View the [source of this content](http://github.github.com/github-flavored-markdown/sample_content.html)._

Let's get the whole "linebreak" thing out of the way. The next paragraph contains two phrases separated by a single newline character:

Roses are red
Violets are blue

The next paragraph has the same phrases, but now they are separated by two spaces and a newline character:

Roses are red  
Violets are blue

Oh, and one thing I cannot stand is the mangling of words with multiple underscores in them like perform_complicated_task or do_this_and_do_that_and_another_thing.

## A bit of the GitHub spice

In addition to the changes in the previous section, certain references are auto-linked:
- SHA: be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User@SHA ref: mojombo@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- User/Project@SHA: mojombo/god@be6a8cc1c1ecfe9489fb51e4869af15a13fc2cd2
- #Num: #1
- User/#Num: mojombo#1
- User/Project#Num: mojombo/god#1

These are dangerous goodies though, and we need to make sure email addresses don't get mangled:

My email addy is tom@github.com.

## Math is hard, let's go shopping

In first grade I learned that 5 > 3 and 2 < 7. Maybe some arrows. 1 -> 2 -> 3. 9 <- 8 <- 7.

Triangles man! a^2 + b^2 = c^2

## We all like making lists

The above header should be an H2 tag. Now, for a list of fruits:
- Red Apples
- Purple Grapes
- Green Kiwifruits

Let's get crazy:
1.  This is a list item with two paragraphs. Lorem ipsum dolor
   sit amet, consectetuer adipiscing elit. Aliquam hendrerit
   mi posuere lectus.
   
   Vestibulum enim wisi, viverra nec, fringilla in, laoreet
   vitae, risus. Donec sit amet nisl. Aliquam semper ipsum
   sit amet velit.
2.  Suspendisse id sem consectetuer libero luctus adipiscing.

What about some code **in** a list? That's insane, right?
1. In Ruby you can map like this:
   
   ```
   ['a', 'b'].map { |x| x.uppercase }
   ```
2. In Rails, you can do a shortcut:
   
   ```
   ['a', 'b'].map(&:uppercase)
   ```

Some people seem to like definition lists

<dl>
  <dt>Lower cost</dt>
  <dd>The new version of this product costs significantly less than the previous one!</dd>
  <dt>Easier to use</dt>
  <dd>We've changed the product so that it's much easier to use!</dd>
</dl>

## I am a robot

Maybe you want to print `robot` to the console 1000 times. Why not?

```
def robot_invasion
  puts("robot " * 1000)
end
```

You see, that was formatted as code because it's been indented by four spaces.

How about we throw some angle braces and ampersands in there?

```
<div class="footer">
    &copy; 2004 Foo Corporation
</div>
```

## Set in stone

Preformatted blocks are useful for ASCII art:

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-< 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>

## Playing the blame game

If you need to blame someone, the best way to do so is by quoting them:

> I, at any rate, am convinced that He does not throw dice.

Or perhaps someone a little less eloquent:

> I wish you'd have given me this written question ahead of time so I
> could plan for it... I'm sure something will pop into my head here in
> the midst of this press conference, with all the pressure of trying to
> come up with answer, but it hadn't yet...
> 
> I don't want to sound like
> I have made no mistakes. I'm confident I have. I just haven't - you
> just put me under the spot here, and maybe I'm not as quick on my feet
> as I should be in coming up with one.

## Table for two

<table>
  <tr>
    <th>ID</th><th>Name</th><th>Rank</th>
  </tr>
  <tr>
    <td>1</td><td>Tom Preston-Werner</td><td>Awesome</td>
  </tr>
  <tr>
    <td>2</td><td>Albert Einstein</td><td>Nearly as awesome</td>
  </tr>
</table>

## Crazy linking action

I get 10 times more traffic from [Google](http://google.com/) than from
[Yahoo](http://search.yahoo.com/) or [MSN](http://search.msn.com/).

**Comment by wshb2154** [comment]
test
﹉﹉
﹉﹉

**Comment by wshb2154** [comment]
> test
> test

**Comment by michaelhood** [comment]
so is there a way to do the math/exponents/super, or no? seems they didn't work 3 years ago and don't now. :)

**Comment by bobodeng** [comment]
#21 test

<pre>
hi
</pre>

**Comment by justjavac** [comment]
测试一下中文：
- [x] @justjavac, **格式化代码**
- [x] 这是一个中文测试
- [x] **加粗**
- [ ] 未完成

**Comment by Lmpessoa** [comment]
I wanted to try to do some enhanced format using HTML tags for the README pages of my projects but it seems the GFM ignores style tags and attributes. Is there any other way to do it?

**Comment by FichteFoll** [comment]
I think ignoring &lt;style&gt; tags is perfectly valid in this case because you can do various and unwanted stuff with it.

I recommend you to take a look at the [Github Pages](http://help.github.com/pages) feature.

**Comment by alick** [comment]
No inner word embolden: e_X_change

**Comment by Zteve** [comment]
OK, so what's with the mess around the <pre> block?

## Set in stone

Preformatted blocks are useful for ASCII art:

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-< 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>

## Playing the blame game

If you need to blame someone, the best way to do so is by quoting them:

> I, at any rate, am convinced that He does not throw dice.

</pre>

We don't seem to end the block in the right place, do we?  Why is that?

Well, it's because of the < in the ascii art.  Is this a parsing error?  Replace it with &lt; to see:

Preformatted blocks are useful for ASCII art:

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-&lt; 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>

and we seem ok now.

Writing \< doesn't work, as you'd expect.

**Comment by maxc01** [comment]
:ship: 
i like this.
And just a test.

**Comment by tjimwalter** [comment]
I don't believe the github wiki feature allows embedded HTML at all. Security issue intended to prevent insertion of malicious javascript. This is unfortunate since embedded HTML is a standard way to do tables in markdown. Github Flavored Markdown (GFM) supports tables, but this makes editing your content (e.g. with a desktop markdown editor ) pretty difficult since markdown editors don't support GFM!

**Comment by FichteFoll** [comment]
Not all HTML tags are &lt;script&gt; tags. Using &lt;em&gt; to <em>emphasize text</em> is perfectly valid. You can also used &lt;table&gt; tags for tables (iirc). (And there are for sure text editors who support Multimarkdown tables (e.g. for Sublime Text there is a plugin).)

(<del>strikeout</del> using &lt;del&gt;)

**Comment by ronggenliu** [comment]
## test

**Comment by huzheng** [comment]
# Try GFM

``` python
def hello():
    print 'hello world'
if __name__ == '__main__':
    print hello()
```

**Comment by Colin6618** [comment]
# try gfm
- try gfm

mm

**Comment by armandas** [comment]
<sup>Superscript</sup> test.

```
<sup>Superscrip</sup> test.
```

**Comment by Logopher** [comment]
I wish [reference links][1] would work.

[1]: They don't.

**Comment by exhibit** [comment]
``` js
alert("hello world")
```

**Comment by ghost** [comment]
```
for (i=1; i <=100; i++){
   Console.WriteLine("Not much going on here");
}
```

**Comment by mrienstra** [comment]
Jesdisciple commented a month ago:

> I wish [reference links][1] would work.
> 
> [1]: They don't.

Do you mean "I wish reference links would work without a link"?

This markdown:

```
Working: [2], [3], [4]. Failing: [5], [6], [7], [8]

[2]: http://github.com/ "This works."
[3]: http://github.com/ 'Works.'
[4]: http://github.com/
[5]: http://github.com/ Fails
[6]: "Fails."
[7]: 'Fails.'
[8]: Fails.
```

Generates the following HTML:

```
<p>Working: <a href="https://github.com/" title="This works.">2</a>, <a href="https://github.com/" title="Works.">3</a>, <a href="https://github.com/">4</a>. Failing: [5], <a href="%22Fails.%22">6</a>, <a href="'Fails.'">7</a>, <a href="Fails.">8</a></p>
```

Which looks like so:

Working: [2](http://github.com/), [3](http://github.com/), [4](http://github.com/). Failing: [5], [6]("Fails."), [7]('Fails.'), [8](Fails.)

[5]: http://github.com/ Fails

---

Huh, here is an interesting bug:

Markdown:

```
[9], [10], [11], [12].

[9]: file://google.com/foo "Fails interestingly."
[10]: ftp://google.com/foo "Fails interestingly."
[11]: ssh://google.com/foo "Fails interestingly."
[12]: foo://google.com/foo "Fails interestingly."
```

HTML source:

```
<p><a title="Fails interestingly.">9</a>, <a title="Fails interestingly.">10</a>, <a title="Fails interestingly.">11</a>, <a title="Fails interestingly.">12</a>.</p>
```

HTML:

[9](file://google.com/foo), [10](ftp://google.com/foo), [11](ssh://google.com/foo), [12](foo://google.com/foo).

**Comment by Logopher** [comment]
Woops, looks like I misread the markdown syntax page; I was thinking reference links were footnotes (intra-page links), but they're just ordinary external links.

(But that would be "I wish reference links would work without a URL.")

**Comment by anndaming** [comment]
for test 

``` ruby
    def say_hi
        print "hello world" 
    end
```

**Comment by jerone** [comment]
What's happening to the ASCII art?

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-< 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>

</pre>
_Update:_
Found the reason, it's because of the `<` in the ASCII art. Replace it with `&lt;` to fix:

<pre>
             ,-. 
    ,     ,-.   ,-. 
   / \   (   )-(   ) 
   \ |  ,.>-(   )-&lt; 
    \|,' (   )-(   ) 
     Y ___`-'   `-' 
     |/__/   `-' 
     | 
     | 
     |    -hrr- 
  ___|_____________ 
</pre>

**Comment by CHANBOLA** [comment]
please,, anyone who knows my password and my user name,,, please let me know ... i beg ..

**Comment by lauriezc** [comment]
testing

---

---

**Comment by trjones1** [comment]
# Fish Types

| Red Fish | Blue Fish |
| --- | --- |
| One Fish | Two Fish |
